name: CI-CD-Pipeline-to-AWS-ElasticBeanStalk

on:
  push:
    branches:
      - master

# env:
#   EB_PACKAGE_S3_BUCKET_NAME: "zzz-ecommerce-app"
#   EB_APPLICATION_NAME      : "myecommapp"
#   EB_ENVIRONMENT_NAME      : "Myecommapp-env"
#   DEPLOY_PACKAGE_NAME      : "ecommerce-app-${{github.sha}}.zip"
#   AWS_REGION_NAME          : "us-west-1"

jobs:
  deploy: 
    name: my_ci_pipeline
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node: [ 12.x ]
    
    steps:
      - name: Git clone our repository
        uses: actions/checkout@v1

      - name: Setup node 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
        run: npm ci
        run: npm run build --if-present
        run: npm test

      - name: Create ZIP deployment package
        run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x  *.git*

      - name: Configure AWS Credentials
        uses: aws-actions-configure-aws-credentials@v1
        with: 
           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Copy our Deployment to S3 Bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

      - name: Print nice message on completion of CI Pipeline
        echo: "CI Pipeline part finished successfully"


